In [100]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [101]:
df = pd.read_csv('/content/titanic_toy.csv')

In [102]:
df

Age     Fare  Family  Survived
0    22.0   7.2500       1         0
1    38.0  71.2833       1         1
2    26.0   7.9250       0         1
3    35.0  53.1000       1         1
4    35.0   8.0500       0         0
..    ...      ...     ...       ...
886  27.0  13.0000       0         0
887  19.0  30.0000       0         1
888   NaN  23.4500       3         0
889  26.0      NaN       0         1
890  32.0   7.7500       0         0

[891 rows x 4 columns]

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       714 non-null    float64
 1   Fare      846 non-null    float64
 2   Family    891 non-null    int64  
 3   Survived  891 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 28.0 KB


In [104]:
df.isnull().mean()*100

Age         19.865320
Fare         5.050505
Family       0.000000
Survived     0.000000
dtype: float64

In [105]:
x = df.drop(columns=['Survived'])
y = df['Survived']


In [106]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [107]:
x_train.shape,x_test.shape

((712, 3), (179, 3))

In [108]:
si_age = SimpleImputer(strategy='constant',fill_value=99)
si_fare = SimpleImputer(strategy='constant',fill_value=999)

In [109]:
trf = ColumnTransformer([
    ('si_age',si_age,['Age']),
    ('si_fare',si_fare,['Fare'])
],remainder='passthrough')

In [114]:
x_train_transformed = trf.fit_transform(x_train)
x_test_transformed = trf.transform(x_test)

In [118]:
trf.named_transformers_['si_age'].statistics_

array([99.])

In [120]:
trf.named_transformers_['si_fare'].statistics_

array([999.])

In [121]:
x_train_transformed

array([[ 45.5   ,  28.5   ,   0.    ],
       [ 23.    ,  13.    ,   0.    ],
       [ 32.    ,   7.925 ,   0.    ],
       ...,
       [ 41.    , 999.    ,   2.    ],
       [ 14.    , 120.    ,   3.    ],
       [ 21.    ,  77.2875,   1.    ]])

In [122]:
x_test_transformed

array([[9.900000e+01, 1.524580e+01, 2.000000e+00],
       [3.100000e+01, 1.050000e+01, 0.000000e+00],
       [2.000000e+01, 7.925000e+00, 0.000000e+00],
       [6.000000e+00, 3.300000e+01, 1.000000e+00],
       [1.400000e+01, 1.124170e+01, 1.000000e+00],
       [2.600000e+01, 7.885000e+01, 0.000000e+00],
       [9.900000e+01, 7.750000e+00, 0.000000e+00],
       [1.600000e+01, 1.800000e+01, 2.000000e+00],
       [1.600000e+01, 7.750000e+00, 0.000000e+00],
       [1.900000e+01, 2.628330e+01, 2.000000e+00],
       [3.700000e+01, 5.310000e+01, 1.000000e+00],
       [4.400000e+01, 8.050000e+00, 0.000000e+00],
       [9.900000e+01, 2.546670e+01, 4.000000e+00],
       [3.000000e+01, 7.225000e+00, 0.000000e+00],
       [3.600000e+01, 1.300000e+01, 0.000000e+00],
       [1.600000e+01, 3.940000e+01, 1.000000e+00],
       [4.200000e+01, 5.255420e+01, 1.000000e+00],
       [9.900000e+01, 7.829200e+00, 0.000000e+00],
       [2.700000e+01, 1.300000e+01, 0.000000e+00],
       [4.700000e+01, 5.200000e